### PR TITLE
Incorporate Eslint

### PR DESCRIPTION
**Pull request by IanVS**
This adds ESLint with rules mainly from [standard](https://github.com/feross/eslint-config-standard), with a few modifications, specifically:

```
"consistent-return"          : 2,
"no-use-before-define"       : 2,
"semi"                       : [2, "always"],
"key-spacing"                : [2, {"align": "colon"}],
"no-multiple-empty-lines"    : [2, {"max": 2}],
"no-multi-spaces"            : [2, {exceptions: {"VariableDeclarator": true}}],
"eqeqeq"                     : [2, "smart"],
"wrap-iife"                  : [2, "inside"],
"brace-style"                : [2, "1tbs"],
"space-before-function-paren": [2, {
                                 "anonymous" : "always",
                                 "named" : "never"
                               }]
```

@jamemackson: Please take a look and see if you agree with the styles here.  I'm not married to any of them if you'd rather use a different style or rule setting.

### CODE REVIEW

**Comment by IanVS** [comment]
@jamemackson Would you mind taking a look at this and merging if you like it, before the codebase diverges too much more?

**Comment by jamemackson** [comment]
Yes, sorry I didn't think about the grander implications of the switch to semantic and pods that is going on in the semantic-ui branch.  I'll merge this and rebase that branch tonight.  

While we on the topic of linting though, what editor are you typically using these days?  I have been using atom more and more lately and I have an eslint package running there but I haven't quite mastered the config for taming down some of the rules - out of the box they are a bit obnoxious. Maybe merging this in will solve the problem though.

**Comment by IanVS** [comment]
I am still using Sublime.  I paid for it not that long ago, and I've got it set up the way I like, so I don't really feel like switching even though everyone raves about Atom.  If it works at all like Sublime linter, this merge should solve your problems, as it should use the .eslintrc closest to the code (traversing up to subsequent parents if it doesn't find one, up to root of the machine).

**Comment by jamemackson** [comment]
That's right.  I think you've told me that before.  I might give that a try one of these days.  

And yea, hopefully it does fix the linting in atom.  

Atom has been pretty good so far but there are aspects of it I don't love. It seems pretty powerful with how customizable it is but it seems like there is some learning curve to take advantage of that which I don't really have time for right now...

**Pull request merged**
